language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.torch/models

matrix:
  include:
    - python: 3.6

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytorch-cpu torchvision-cpu -c pytorch
  - pip install .[tests]
  - pip install pycodestyle

script:
  - pytest tests/test_pretrained_models.py::test_nasnetalarge_model -s
  - pytest tests/test_pretrained_models.py::test_nasnetamobile_model -s
  - pytest tests/test_pretrained_models.py::test_pnasnet5large_model -s
